"""Initial migration

Revision ID: 7d9194c9637d
Revises: 
Create Date: 2026-01-17 16:39:35.680905+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d9194c9637d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('barcode', sa.String(length=13), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('ingredients_text', sa.Text(), nullable=True),
    sa.Column('ingredients_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nutriments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nutrition_grades', sa.String(length=1), nullable=True),
    sa.Column('nova_group', sa.Integer(), nullable=True),
    sa.Column('ecoscore_grade', sa.String(length=1), nullable=True),
    sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_table('normalized_nutrition',
    sa.Column('calories_100g', sa.Float(), nullable=True),
    sa.Column('protein_100g', sa.Float(), nullable=True),
    sa.Column('carbohydrates_100g', sa.Float(), nullable=True),
    sa.Column('sugars_100g', sa.Float(), nullable=True),
    sa.Column('fat_100g', sa.Float(), nullable=True),
    sa.Column('saturated_fat_100g', sa.Float(), nullable=True),
    sa.Column('fiber_100g', sa.Float(), nullable=True),
    sa.Column('sodium_100g', sa.Float(), nullable=True),
    sa.Column('salt_100g', sa.Float(), nullable=True),
    sa.Column('serving_size', sa.String(length=50), nullable=True),
    sa.Column('serving_quantity', sa.Float(), nullable=True),
    sa.Column('nutrition_score_fr_100g', sa.Integer(), nullable=True),
    sa.Column('nutrition_score_fr', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('normalized_nutrition')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
