"""add missing columns to normalized_nutrition

Revision ID: 82af0efad759
Revises: 8818b9492018
Create Date: 2026-01-18 13:09:45.949977+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82af0efad759'
down_revision: Union[str, Sequence[str], None] = '8818b9492018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normalized_nutrition', sa.Column('general_health_score', sa.Integer(), nullable=True))
    op.add_column('normalized_nutrition', sa.Column('nutri_grade', sa.String(length=1), nullable=True))
    op.drop_index(op.f('ix_normalized_nutrition_knn'), table_name='normalized_nutrition')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_normalized_nutrition_knn'), 'normalized_nutrition', ['sugars_100g', 'sodium_100g', 'protein_100g', 'fiber_100g'], unique=False)
    op.drop_column('normalized_nutrition', 'nutri_grade')
    op.drop_column('normalized_nutrition', 'general_health_score')
    # ### end Alembic commands ###
