"""restore dropped indexes

Revision ID: cd08fc4abd93
Revises: 82af0efad759
Create Date: 2026-01-18 13:12:13.924210+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd08fc4abd93'
down_revision: Union[str, Sequence[str], None] = '82af0efad759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create single-column indexes on products table
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    
    # Create composite index for KNN search on normalized_nutrition
    op.create_index(
        'ix_normalized_nutrition_knn',
        'normalized_nutrition',
        ['sugars_100g', 'sodium_100g', 'protein_100g', 'fiber_100g'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes in reverse order of creation
    op.drop_index('ix_normalized_nutrition_knn', table_name='normalized_nutrition')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    # ### end Alembic commands ###
